import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        // ENGLISH LANGUAGE
        'en_US': {
          'hello': 'Hello World',
          'message': 'Welcome to Proto Coders Point',
          'title': 'Flutter Language - Localization',
          'sub': 'Subscribe Now',
          'changelang': 'Change Language',
          'language': 'Language',
          'products': 'Products',
          'messages': 'Messages',
          'gallery': 'Gallery',
          'feedback': 'Feedback',
          'users': 'Users',
          'home': 'Home',
          'show_design': 'Show your design',
          'post': 'Post',
          'image_upload_failed': 'Image upload failed.',
          'for_you': 'For you',
          'following': 'Following',
          'nothing_here': 'Nothing here',
          'failed_to_upload_image': 'Failed to upload image',
          'welcome': 'Welcome',
          'settings': 'Settings',
          'logout': 'Logout',
          'Edit bio': 'Edit bio',
          'Save': 'Save',
          'category': 'Category: ',
          'brand': 'Brand: ',
          'price': 'Price: \$',
          'description': 'Description: ',
          'close': 'Close',
          'designers': 'Designers',
          'add_new_designer': 'Add New Designer',
          'edit_designer': 'Edit Designer',
          'user': 'User',
          'full_name': 'Full Name',
          'years_of_experience': 'Years of Experience',
          'specialization': 'Specialization',
          'add': 'Add',
          'update': 'Update',
          'cancel': 'Cancel',
          'loading': 'Loading...',
          'error': 'Error',
          'no_designers': 'No designers available.',
          'failed_to_load_designer': 'Failed to load designer: ',
          'failed_to_save_designer': 'Failed to save designer: ',
          'failed_to_delete_designer': 'Failed to delete designer: ',
          'an_error_occurred': 'An error occurred: ',
          'type_a_message': 'Type a message',
          'feedback_message': 'Feedback Message',
          'feedback_management': 'Feedback Management',
          'something_went_wrong': 'Something went wrong',
          'write_a_reply': 'Write a reply...',
          'add_product': 'Add Product',
          'update_product': 'Update Product',
          'product_name': 'Product Name',
          'choose_image': 'Choose Image',
          'failed_to_delete_product': 'Failed to delete product: ',
          'no_products_available': 'No products available.',
          'failed_to_save_product': 'Failed to save product: ',
          'failed_to_load_product': 'Failed to load product: ',
          'uncategorized': 'Uncategorized',
          'search_users': 'Search Users...',
          'categories_management': 'Categories Management',
          'no_categories_available': 'No categories available.',
          'add_new_category': 'Add New Category',
          'name': 'Name',
          'active': 'Active',
          'edit_category': 'Edit Category',
          'confirm_deletion': 'Confirm Deletion',
          'delete_confirmation':
              'Are you sure you want to delete this category?',
          'delete': 'Delete',
          'show_your_design': 'Show your design',
          'image_picked': 'Image Picked!',
          'Item_added': 'Item added',
          'dark_mode': 'Dark Mode',
          'blocked_users': 'Blocked Users',
          'accounts_setting': 'Accounts setting',
          'english': 'English',
          'vietnamese': 'Tiếng Việt',
          'delete_account': 'Delete Account?',
          'confirm_delete': 'Are you sure you want to delete your account?',
          'account_settings': 'Account Settings',
          'delete_account_button': 'Delete Account',
          'unlock': 'Unlock',
          'confirm_unlock': 'Do you want to unlock this user?',
          'unblock': 'Unblock',
          'unblock_success': 'Unblock successfully!',
          'no_blocked_users': 'No blocked users..',
          'H O M E': 'H O M E',
          'P R O F I L E': 'P R O F I L E',
          'S E A R C H': 'S E A R C H',
          'S E T T I N G S': 'S E T T I N G S',
          'F E E D B A C K': 'F E E D B A C K',
          'A D M I N': 'A D M I N',
          'L O G O U T': 'L O G O U T',
          'edit_bio': 'Edit bio..',
          'save': 'Save',
          'unfollow': 'Unfollow',
          'unfollowing_message': 'Unfollowing this user?',
          'yes': 'Yes',
          'no_posts': 'No posts..',
          'bio': 'Bio',
          'designs': 'Designs',
          'please_enter_name': 'Please enter your name.',
          'please_enter_email': 'Please enter your email address.',
          'please_enter_password': 'Please enter your password.',
          'passwords_do_not_match': "Passwords don't match",
          'register': 'Register',
          'email': 'Email',
          'password': 'Password',
          'confirm_password': 'Confirm password',
          'have_account': 'Have an account?',
          'login_here': 'Login Here',
          'reviews': 'Reviews',
          'no_reviews_available': 'No reviews available.',
          'add_review': 'Add Review',
          'update_review': 'Update Review',
          'product': 'Product',
          'designer': 'Designer',
          'comment': 'Comment',
          'failed_to_delete_review': 'Failed to delete review: ',
          'failed_to_save_review': 'Failed to save review: ',
          'failed_to_load_review': 'Failed to load review: ',
          'update_user': 'Update User',
          'validation_error': 'Validation Error',
          'name_email_required': 'Name and Email are required.',
          'user_updated_successfully': 'User updated successfully',
          'delete_user_confirmation':
              'Are you sure you want to delete this user?',
          'user_deleted_successfully': 'User deleted successfully',
          'failed_to_delete_user': 'Failed to delete user. Please try again.',
          'no_users_found': 'No users found.',
          'role': 'Role',
          'hint_password': 'Leave blank to keep current password',
          'user_role': 'User',
          'admin_role': 'Admin',
          'overview': 'Overview',
          'trends': 'Trends',
          'categories': 'Categories',
          'price_range_distribution': 'Price Range Distribution',
          'recently_added_products': 'Recently Added Products',
          'new_products': 'New Products',
          'total_products': 'Total Products',
          'no_data_for_comparison': 'No data for comparison',
          'date_unknown': 'Date unknown',
          'product_addition_trend': 'Product Addition Trend',
          'brand_distribution': 'Brand Distribution',
          'vs_last_week': 'vs last week',
          'this_month': 'this month',
          'error_loading_categories': 'Error loading categories',
          'no_categories_found': 'No categories found',
          'unnamed_category': 'Unnamed Category',
          'no_description': 'No description',
          'products_in_this_category': 'Products in this category:',
          'no_products_in_this_category': 'No products in this category',
          'unknown_brand': 'Unknown Brand',
          'unnamed_product': 'Unnamed Product',
          'no_products_found': 'No products found',
          'submit_feedback': 'Submit Feedback',
          'feedback_submitted': 'Feedback submitted successfully',
          'something_wrong': 'Something went wrong',
          'rating': 'Rating:',
          'reply_from': 'Reply from:',
          'write_reply': 'Write a reply...',
          'no_feedback_found': 'No feedback found',
          'recording': 'Recording...',
          'tap_to_record': 'Tap the mic icon to start recording',
          'please_select_category': 'Please select a category',
          'no_comments_yet': 'No comments yet..',
          'report_management': 'Report Management',
          'username': 'Username',
          'timestamp': 'Timestamp',
          'notification': 'Notification',
          'login': 'Login',
          'forgot_password': 'Forgot Password?',
          'enter_email': 'Please enter your email address.',
          'enter_password': 'Please enter your password.',
          'email_password_error': 'Something wrong with your email/password',
          'google_signin_error': "There's something wrong...",
          'dont_have_account': "Don't have an account?",
          'register_here': 'Register Here',
          'enter_your_email': 'Enter your email:',
          'invalid_email': 'Invalid email address.',
          'password_reset_link_sent': 'Password reset link sent successfully.',
          'failed_to_send_reset_link': 'Failed to send password reset link',
          'reset_password': 'Reset password',
          'followers': 'Followers',
          'no_followers': 'No Followers',
          'no_following': 'No Following',
          'users_dashboard': 'Users Dashboard',
          'statistics': 'Statistics',
          'manage_users': 'Manage Users',
          'weekly_new_users': 'Weekly New Users',
          'monthly_new_users': 'Monthly New Users',
          'yearly_new_users': 'Yearly New Users',
          'monthly_retention': 'Monthly Retention',
          'weekly_growth_trend': 'Weekly Growth Trend',
          'recent_new_users': 'Recent New Users',
          'error_loading_retention': 'Error loading retention',
          'no_feedback_data_available': 'No feedback data available',
          'export_data': 'Export Data',
          'feedback_volume_trend': 'Feedback Volume Trend',
          'category_distribution': 'Category Distribution',
          'total_feedback': 'Total Feedback',
          'average_rating': 'Average Rating',
          'sentiment_analysis': 'Sentiment Analysis',
          'recent_feedback': 'Recent Feedback',
          'no_message': 'No message',
          'Item_already_exists': 'Item already exists',
          'n/a': 'N/A',
          'bug': 'Bug',
          'feature': 'Feature',
          'ui_ux': 'UI/UX',
          'other': 'Other',
          'data_exported_successfully': 'Data exported successfully',
          'consultations': 'Consultations',
          'add_new_consultation': 'Add New Consultation',
          'edit_consultation': 'Edit Consultation',
          'status': 'Status',
          'select_date': 'Select Date',
          'date': 'Date',
          'failed_to_load_consultation': 'Failed to load consultation',
          'failed_to_save_consultation': 'Failed to save consultation',
          'no_consultations_available': 'No consultations available',
          'failed_to_delete_consultation': 'Failed to delete consultation',
          'schedule_date': 'Schedule Date',
          'actions': 'Actions',
          'failed_to_delete_note': 'Failed to delete note',
          'no_notes_available': 'No notes available.',
          'Day': 'Day',
          'Week': 'Week',
          'Month': 'Month',
          'Year': 'Year',
          'Total Products': 'Total Products',
          'Category': 'Category',
          'Price Range Distribution': 'Price Range Distribution',
          'Recently Added Products': 'Recently Added Products',
          'Product Addition Trend': 'Product Addition Trend',
          'Products': 'Products',
          'Feedbacks': 'Feedbacks',
          'Users': 'Users',
          'Reports': 'Reports',
          'Users Dashboard': 'Users Dashboard',
          'Statistics': 'Statistics',
          'Manage Users': 'Manage Users',
          'Weekly New Users': 'Weekly New Users',
          'Monthly New Users': 'Monthly New Users',
          'Yearly New Users': 'Yearly New Users',
          'Monthly Retention': 'Monthly Retention',
          'Weekly Growth Trend': 'Weekly Growth Trend',
          'Recent New Users': 'Recent New Users',
          'Error loading retention': 'Error loading retention', // Nếu cần
          'Error loading dashboard data:':
              'Error loading dashboard data:', // Nếu cần
          'Overview': 'Overview',
          'Trends': 'Trends',
          'Design': 'Design',
          'Categories': 'Categories',
          'Add Products': 'Add Products',
          'Week 1': 'Week 1',
          'Week 2': 'Week 2',
          'Week 3': 'Week 3',
          'Week 4': 'Week 4',
          'User Statistics': 'User Statistics',
          'Infinity': 'Infinity',
          'Role': 'Role:',
          'Feedback Statistics': 'Feedback Statistics',
          'Feedback Management': 'Feedback Management',
          'Total Feedback': 'Total Feedback',
          'Average Rating': 'Average Rating',
          ' +0.3 vs last week': ' +0.3 vs last week',
          'Sentiment Analysis': 'Sentiment Analysis',
          'Positive': 'Positive',
          'Neutral': 'Neutral',
          'Negative': 'Negative',
          'Recent Feedback': 'Recent Feedback',
          'Feedback Volume Trend': 'Feedback Volume Trend',
          'Category Distribution': 'Category Distribution',
          'Bug': 'Bug',
          'Feature': 'Feature',
          'Other': 'Other',
          'Rating:': 'Rating:',
          'Add Product': 'Add Product',
          'This Month': 'this month', // Để sử dụng trong câu
          'Advanced Analytics Dashboard': 'Advanced Analytics Dashboard',
          'Gallery': 'Gallery',
          'Message': 'Message',
          'Home': 'Home',
          'Background': 'Backgrounds',
          'Choose_your_background': 'Choose your background',
          'Please_select_background': 'Please select background',
          'Products list to design': 'Products list to design',
          'go_add_product' : 'Go to products list to add more',
          'Our background' : 'Our background',
          'Your background' : 'Your background',
          'Image upload failed': 'Image upload failed.',
          'For you': 'For you',
          'Following': 'Following',
          'Failed to upload image': 'Failed to upload image',
          'Add new designer': 'Add New Designer',
          'Edit designer': 'Edit Designer',
          'User': 'User',
          'Full name': 'Full Name',
          'Years of experience': 'Years of Experience',
          'Specialization': 'Specialization',
          'Loading': 'Loading...',
          'No designers': 'No designers available.',
          'Failed to load designer': 'Failed to load designer: ',
          'Failed to save designer': 'Failed to save designer: ',
          'Failed to delete designer': 'Failed to delete designer: ',
          'An error occurred': 'An error occurred: ',
          'Type a message': 'Type a message',
          'Feedback Message': 'Feedback Message',
          'Something went wrong': 'Something went wrong',
          'Write a reply': 'Write a reply...',
          'Add product': 'Add Product',
          'Update product': 'Update Product',
          'Product Name': 'Product Name',
          'Choose Image': 'Choose Image',
          'Failed to delete product': 'Failed to delete product: ',
          'No products available': 'No products available.',
          'Failed to save product': 'Failed to save product: ',
          'Failed to load product': 'Failed to load product: ',
          'Search Users': 'Search Users...',
          'Categories Management': 'Categories Management',
          'No categories available': 'No categories available.',
          'Add new category': 'Add New Category',
          'Edit Category': 'Edit Category',
          'Confirm Deletion': 'Confirm Deletion',
          'Delete confirmation':
          'Are you sure you want to delete this category?',
          'Delete': 'Delete',
          'Show your design': 'Show your design',
          'Image picked': 'Image Picked!',
          'Item added': 'Item added',
          'Dark Mode': 'Dark Mode',
          'Blocked Users': 'Blocked Users',
          'Accounts setting': 'Accounts setting',
          'Delete Account': 'Delete Account?',
          'Confirm delete': 'Are you sure you want to delete your account?',
          'Account Settings': 'Account Settings',
          'Delete account button': 'Delete Account',
          'Confirm unlock': 'Do you want to unlock this user?',
          'Unblock success': 'Unblock successfully!',
          'No blocked users': 'No blocked users..',
          'Unfollowing message': 'Unfollowing this user?',
          'yes': 'Yes',
          'no_posts': 'No posts..',
          'No posts': 'No posts..',
          'bio': 'Bio',
          'Bio': 'Bio',
          'designs': 'Designs',
          'Designs': 'Designs',
          'please_enter_name': 'Please enter your name.',
          'please_enter_email': 'Please enter your email address.',
          'please_enter_password': 'Please enter your password.',
          'passwords_do_not_match': "Passwords don't match",
          'Please enter name': 'Please enter your name.',
          'Please enter email': 'Please enter your email address.',
          'Please enter password': 'Please enter your password.',
          'Passwords do not match': "Passwords don't match",
          'Register': 'Register',
          'Password': 'Password',
          'Confirm password': 'Confirm password',
          'Have account': 'Have an account?',
          'Login Here': 'Login Here',
          'Reviews': 'Reviews',
          'No reviews available': 'No reviews available.',
          'Add review': 'Add Review',
          'Update review': 'Update Review',
          'Product': 'Product',
          'Designer': 'Designer',
          'Comment': 'Comment',
          'Failed to delete review:': 'Failed to delete review: ',
          'Failed to save review:': 'Failed to save review: ',
          'Failed to load review:': 'Failed to load review: ',
          'Update User': 'Update User',
          'Validation Error': 'Validation Error',
          'Name and Email are required.': 'Name and Email are required.',
          'User updated successfully': 'User updated successfully',
          'Are you sure you want to delete this user?':
          'Are you sure you want to delete this user?',
          'User deleted successfully': 'User deleted successfully',
          'Failed to delete user. Please try again.':
          'Failed to delete user. Please try again.',
          'No users found.': 'No users found.',
          'Hint password': 'Leave blank to keep current password',
          'User Role': 'User',
          'Admin role': 'Admin',
          'New Products': 'New Products',
          'No data for comparison': 'No data for comparison',
          'Date unknown': 'Date unknown',
          'Brand Distribution': 'Brand Distribution',
          'vs last week': 'vs last week',
          'this month': 'this month',
          'Error loading categories': 'Error loading categories',
          'No categories found': 'No categories found',
          'Unnamed Category': 'Unnamed Category',
          'No description': 'No description',
          'Products in this category:': 'Products in this category:',
          'No products in this category': 'No products in this category',
          'Unknown Brand': 'Unknown Brand',
          'Unnamed Product': 'Unnamed Product',
          'No products found': 'No products found',
          'Submit Feedback': 'Submit Feedback',
          'Feedback submitted successfully': 'Feedback submitted successfully',
          'Rating': 'Rating:',
          'Reply from:': 'Reply from:',
          'Write a reply...': 'Write a reply...',
          'No feedback found': 'No feedback found',
          'Recording': 'Recording...',
          'Tap the mic icon to start recording': 'Tap the mic icon to start recording',
          'Please select a category': 'Please select a category',
          'No comments yet..': 'No comments yet..',
          'Report Management': 'Report Management',
          'Username': 'Username',
          'Timestamp': 'Timestamp',
          'Notification': 'Notification',
          'Login': 'Login',
          'Failed to load consultation': 'Failed to load consultation',
          'failed to save consultation': 'Failed to save consultation',
          'No consultations available': 'No consultations available',
          'Failed to delete consultation': 'Failed to delete consultation',
          'Schedule date': 'Schedule Date',
          'Failed to delete note': 'Failed to delete note',
          'No notes available': 'No notes available.',
          'Forgot Password?': 'Forgot Password?',
          'Please enter your email address.': 'Please enter your email address.',
          'Please enter your password.': 'Please enter your password.',
          'Something wrong with your email/password': 'Something wrong with your email/password',
          'Theres something wrong...': "There's something wrong...",
          'Dont have an account?': "Don't have an account?",
          'Register Here': 'Register Here',
          'Enter your email:': 'Enter your email:',
          'Invalid email address.': 'Invalid email address.',
          'Password reset link sent successfully.': 'Password reset link sent successfully.',
          'Failed to send password reset link': 'Failed to send password reset link',
          'Reset password': 'Reset password',
          'Followers': 'Followers',
          'No Followers': 'No Followers',
          'No Following': 'No Following',
          'No feedback data available': 'No feedback data available',
          'Export Data': 'Export Data',
          'No message': 'No message',
          'Item already exists': 'Item already exists',
          'Data exported successfully': 'Data exported successfully',
          'Consultations': 'Consultations',
          'Add New Consultation': 'Add New Consultation',
          'Edit Consultation': 'Edit Consultation',
          'Status': 'Status',
          'Select Date': 'Select Date',
          'Date': 'Date',
          'Failed to save consultation': 'Failed to save consultation',
          'Schedule Date': 'Schedule Date',
          'Actions': 'Actions',
          'No notes available.': 'No notes available.',
          'day': 'Day',
          'week': 'Week',
          'month': 'Month',
          'year': 'Year',
          'Error loading dashboard data' : 'Error loading dashboard data', // Nếu cần
          'week 1': 'Week 1',
          'week 2': 'Week 2',
          'week 3': 'Week 3',
          'week 4': 'Week 4',
          'positive': 'Positive',
          'neutral': 'Neutral',
          'negative': 'Negative',
          'rating:': 'Rating:',
          'Choose your background': 'Choose your background',
          'Please select background': 'Please select background',
          'Go to products list to add more': 'Go to products list to add more',
          'Failed to load image': 'Failed to load image',
          'Image View': 'Image View',
          'No link provided': 'No link provided',
          'D E S I G N' : 'D E S I G N',

},
        // VIETNAMESE LANGUAGE
        'vi_VN': {
          'hello': 'Xin chào',
          // 'message': 'Chào mừng đến với Proto Coders Point',
          'title': 'Tiêu đề',
          'sub': 'Đăng ký ngay',
          'changelang': 'Thay đổi ngôn ngữ',
          'language': 'Ngôn ngữ',
          'products': 'Sản phẩm',
          'messages': 'Tin nhắn',
          'gallery': 'Thư viện',
          'feedback': 'Phản hồi',
          'users': 'Người dùng',
          'Home': 'Trang chủ',
          'Feedback': 'Phản hồi',
          'Products': 'Sản phẩm',
          'show_design': 'Hiển thị thiết kế của bạn',
          'post': 'Đăng',
          'image_upload_failed': 'Tải ảnh lên thất bại.',
          'following': 'Đang theo dõi',
          'nothing_here': 'Không có gì ở đây',
          'failed_to_upload_image': 'Tải ảnh lên không thành công',
          'settings': 'Cài đặt',
          'logout': 'Đăng xuất',
          'Edit bio': 'Chỉnh sửa tiểu sử',
          'Save': 'Lưu',
          'for_you': 'Dành cho bạn',
          'category': 'Danh mục: ',
          'brand': 'Thương hiệu: ',
          'price': 'Giá:',
          'description': 'Mô tả: ',
          'Item_already_exists': 'Sản phẩm đã được thêm ',
          'close': 'Đóng',
          'designers': 'Các Nhà Thiết Kế',
          'add_new_designer': 'Thêm Nhà Thiết Kế Mới',
          'edit_designer': 'Chỉnh Sửa Nhà Thiết Kế',
          'user': 'Người Dùng',
          'full_name': 'Họ và Tên',
          'years_of_experience': 'Số Năm Kinh Nghiệm',
          'specialization': 'Chuyên Ngành',
          'add': 'Thêm',
          'Item_added': 'Đã thêm sản phẩm',
          'update': 'Cập Nhật',
          'cancel': 'Hủy',
          'loading': 'Đang Tải...',
          'error': 'Lỗi',
          'Design': 'Thiết kế',
          'no_designers': 'Không có nhà thiết kế nào.',
          'failed_to_load_designer': 'Không thể tải nhà thiết kế: ',
          'failed_to_save_designer': 'Không thể lưu nhà thiết kế: ',
          'failed_to_delete_designer': 'Không thể xóa nhà thiết kế: ',
          'an_error_occurred': 'Đã xảy ra lỗi: ',
          'type_a_message': 'Gõ một tin nhắn',
          'feedback_message': 'Tin Nhắn Phản Hồi',
          'feedback_management': 'Quản Lý Phản Hồi',
          'something_went_wrong': 'Đã xảy ra lỗi',
          'write_a_reply': 'Viết một phản hồi...',
          'add_product': 'Thêm Sản Phẩm',
          'update_product': 'Cập Nhật Sản Phẩm',
          'product_name': 'Tên Sản Phẩm',
          'choose_image': 'Chọn Hình Ảnh',
          'failed_to_delete_product': 'Không thể xóa sản phẩm: ',
          'no_products_available': 'Không có sản phẩm nào.',
          'failed_to_save_product': 'Không thể lưu sản phẩm: ',
          'failed_to_load_product': 'Không thể tải sản phẩm: ',
          'uncategorized': 'Chưa Phân Loại',
          'search_users': 'Tìm Kiếm Người Dùng...',
          'categories_management': 'Quản Lý Danh Mục',
          'no_categories_available': 'Không có danh mục nào.',
          'add_new_category': 'Thêm Danh Mục Mới',
          'name': 'Tên',
          'active': 'Kích Hoạt',
          'edit_category': 'Chỉnh Sửa Danh Mục',
          'confirm_deletion': 'Xác Nhận Xóa',
          'delete_confirmation':
              'Bạn có chắc chắn muốn xóa danh mục này không?',
          'delete': 'Xóa',
          'show_your_design': 'Hiển thị thiết kế của bạn',
          'image_picked': 'Hình ảnh đã được chọn!',
          'dark_mode': 'Chế độ tối',
          'blocked_users': 'Người dùng bị chặn',
          'accounts_setting': 'Cài đặt tài khoản',
          'english': 'Tiếng Anh',
          'vietnamese': 'Tiếng Việt',
          'delete_account': 'Xóa Tài Khoản?',
          'confirm_delete':
              'Bạn có chắc chắn muốn xóa tài khoản của mình không?',
          'account_settings': 'Cài Đặt Tài Khoản',
          'delete_account_button': 'Xóa Tài Khoản',
          'unlock': 'Mở khóa',
          'confirm_unlock': 'Bạn có muốn mở khóa người dùng này không?',
          'unblock': 'Mở khóa',
          'unblock_success': 'Mở khóa thành công!',
          'no_blocked_users': 'Không có người dùng bị chặn..',
          'H O M E': 'T R A N G  C HỦ',
          'P R O F I L E': 'H Ồ  S Ơ',
          'S E A R C H': 'T I M  K I Ế M',
          'S E T T I N G S': 'C À I  ĐẶ T',
          'F E E D B A C K': 'P HẢ N  HỒ I',
          'A D M I N': 'Q UẢ N  T RỊ',
          'L O G O U T': 'Đ Ă N G  X UẤ T',
          'edit_bio': 'Chỉnh sửa tiểu sử..',
          'save': 'Lưu',
          'unfollow': 'Bỏ theo dõi',
          'unfollowing_message':
              'Bạn có muốn bỏ theo dõi người dùng này không?',
          'yes': 'Có',
          'no_posts': 'Không có bài viết..',
          'bio': 'Tiểu sử',
          'designs': 'Thiết kế',
          'please_enter_name': 'Vui lòng nhập tên của bạn.',
          'please_enter_email': 'Vui lòng nhập địa chỉ email của bạn.',
          'please_enter_password': 'Vui lòng nhập mật khẩu của bạn.',
          'passwords_do_not_match': 'Mật khẩu không khớp',
          'register': 'Đăng ký',
          'email': 'Email',
          'password': 'Mật khẩu',
          'confirm_password': 'Xác nhận mật khẩu',
          'have_account': 'Bạn đã có tài khoản?',
          'login_here': 'Đăng nhập tại đây',
          'reviews': 'Đánh giá',
          'no_reviews_available': 'Không có đánh giá nào.',
          'add_review': 'Thêm đánh giá',
          'update_review': 'Cập nhật đánh giá',
          'product': 'Sản phẩm',
          'designer': 'Nhà thiết kế',
          'comment': 'Bình luận',
          'failed_to_delete_review': 'Không thể xóa đánh giá: ',
          'failed_to_save_review': 'Không thể lưu đánh giá: ',
          'failed_to_load_review': 'Không thể tải đánh giá: ',
          'update_user': 'Cập nhật người dùng',
          'validation_error': 'Lỗi xác thực',
          'name_email_required': 'Tên và Email là bắt buộc.',
          'user_updated_successfully': 'Cập nhật người dùng thành công',
          'delete_user_confirmation':
              'Bạn có chắc chắn muốn xóa người dùng này không?',
          'user_deleted_successfully': 'Người dùng đã được xóa thành công',
          'failed_to_delete_user':
              'Không thể xóa người dùng. Vui lòng thử lại.',
          'no_users_found': 'Không tìm thấy người dùng nào.',
          'role': 'Vai trò',
          'hint_password': 'Để trống để giữ mật khẩu hiện tại',
          'user_role': 'Người dùng',
          'admin_role': 'Quản trị viên',
          'overview': 'Tổng quan',
          'trends': 'Xu hướng',
          'categories': 'Danh mục',
          'price_range_distribution': 'Phân phối theo khoảng giá',
          'recently_added_products': 'Sản phẩm vừa thêm',
          'new_products': 'Sản phẩm mới',
          'total_products': 'Tổng số sản phẩm',
          'no_data_for_comparison': 'Không có dữ liệu để so sánh',
          'date_unknown': 'Ngày không xác định',
          'product_addition_trend': 'Xu hướng thêm sản phẩm',
          'brand_distribution': 'Phân phối thương hiệu',
          'vs_last_week': 'so với tuần trước',
          'this_month': 'trong tháng này',
          'error_loading_categories': 'Lỗi khi tải danh mục',
          'no_categories_found': 'Không tìm thấy danh mục',
          'unnamed_category': 'Danh mục không tên',
          'no_description': 'Không có mô tả',
          'products_in_this_category': 'Sản phẩm trong danh mục này:',
          'no_products_in_this_category':
              'Không có sản phẩm trong danh mục này',
          'unknown_brand': 'Thương hiệu không xác định',
          'unnamed_product': 'Sản phẩm không tên',
          'no_products_found': 'Không tìm thấy sản phẩm',
          'submit_feedback': 'Gửi phản hồi',
          'feedback_submitted': 'Phản hồi đã được gửi thành công',
          'something_wrong': 'Có gì đó không đúng',
          'rating': 'Đánh giá:',
          'reply_from': 'Phản hồi từ:',
          'write_reply': 'Viết một phản hồi...',
          'no_feedback_found': 'Không có phản hồi nào',
          'recording': 'Đang ghi âm...',
          'tap_to_record': 'Chạm vào biểu tượng mic để bắt đầu ghi âm',
          'please_select_category': 'Vui lòng chọn một danh mục',
          'no_comments_yet': 'Chưa có bình luận nào..',
          'report_management': 'Quản Lý Báo Cáo',
          'username': 'Tên người dùng',
          'message': 'Tin nhắn',
          'timestamp': 'Thời gian',
          'notification': 'Thông Báo',
          'login': 'Đăng Nhập',
          'forgot_password': 'Quên Mật Khẩu?',
          'enter_email': 'Vui lòng nhập địa chỉ email của bạn.',
          'enter_password': 'Vui lòng nhập mật khẩu của bạn.',
          'email_password_error': 'Có vấn đề với email/mật khẩu của bạn',
          'google_signin_error': 'Có điều gì đó không ổn...',
          'dont_have_account': 'Chưa có tài khoản?',
          'register_here': 'Đăng Ký Tại Đây',
          'enter_your_email': 'Nhập email của bạn:',
          'invalid_email': 'Địa chỉ email không hợp lệ.',
          'password_reset_link_sent':
              'Đã gửi liên kết đặt lại mật khẩu thành công.',
          'failed_to_send_reset_link':
              'Không thể gửi liên kết đặt lại mật khẩu',
          'reset_password': 'Đặt lại mật khẩu',
          'followers': 'Người theo dõi',
          'no_followers': 'Không có người theo dõi',
          'no_following': 'Không có người đang theo dõi',
          'users_dashboard': 'Bảng điều khiển người dùng',
          'statistics': 'Thống kê',
          'manage_users': 'Quản lý người dùng',
          'weekly_new_users': 'Người dùng mới hàng tuần',
          'monthly_new_users': 'Người dùng mới hàng tháng',
          'yearly_new_users': 'Người dùng mới hàng năm',
          'monthly_retention': 'Tỷ lệ giữ chân hàng tháng',
          'weekly_growth_trend': 'Xu hướng tăng trưởng hàng tuần',
          'recent_new_users': 'Người dùng mới gần đây',
          'error_loading_retention': 'Lỗi khi tải dữ liệu giữ chân',
          'no_feedback_data_available': 'Không có dữ liệu phản hồi',
          'export_data': 'Xuất dữ liệu',
          'feedback_volume_trend': 'Xu hướng khối lượng phản hồi',
          'category_distribution': 'Phân phối danh mục',
          'total_feedback': 'Tổng phản hồi',
          'average_rating': 'Đánh giá trung bình',
          'sentiment_analysis': 'Phân tích cảm xúc',
          'recent_feedback': 'Phản hồi gần đây',
          'no_message': 'Không có tin nhắn',
          'n/a': 'Không có',
          'bug': 'Lỗi',
          'feature': 'Tính năng',
          'ui_ux': 'UI/UX',
          'other': 'Khác',
          'data_exported_successfully': 'Dữ liệu đã được xuất thành công',
          'consultations': 'Tư vấn',
          'add_new_consultation': 'Thêm tư vấn mới',
          'edit_consultation': 'Chỉnh sửa tư vấn',
          'status': 'Trạng thái',
          'select_date': 'Chọn ngày',
          'date': 'Ngày',
          'failed_to_load_consultation': 'Lỗi khi tải tư vấn',
          'failed_to_save_consultation': 'Lỗi khi lưu tư vấn',
          'no_consultations_available': 'Không có tư vấn nào',
          'failed_to_delete_consultation': 'Lỗi khi xóa tư vấn',
          'schedule_date': 'Ngày lên lịch',
          'actions': 'Hành động',
          'failed_to_delete_note': 'Lỗi khi xóa ghi chú',
          'no_notes_available': 'Không có ghi chú nào.',
          'Day': 'Ngày',
          'Week': 'Tuần',
          'Month': 'Tháng',
          'Year': 'Năm',
          'Total Products': 'Tổng sản phẩm',
          'New Products': 'Sản phẩm mới',
          'Category': 'Danh mục',
          'Price Range Distribution': 'Phân phối khoảng giá',
          'Recently Added Products': 'Sản phẩm mới thêm',
          'Product Addition Trend': 'Xu hướng bổ sung sản phẩm',
          'Feedbacks': 'Phản hồi',
          'Users': 'Người dùng',
          'Reports': 'Báo cáo',
          'Users Dashboard': 'Bảng điều khiển người dùng',
          'Statistics': 'Thống kê',
          'Manage Users': 'Quản lý người dùng',
          'Weekly New Users': 'Người dùng mới hàng tuần',
          'Monthly New Users': 'Người dùng mới hàng tháng',
          'Yearly New Users': 'Người dùng mới hàng năm',
          'Monthly Retention': 'Tỷ lệ giữ chân hàng tháng',
          'Weekly Growth Trend': 'Xu hướng tăng trưởng hàng tuần',
          'Recent New Users': 'Người dùng mới gần đây',
          'Error loading retention': 'Lỗi khi tải tỷ lệ giữ chân',
          'Error loading dashboard data:':
              'Lỗi khi tải dữ liệu bảng điều khiển:',
          'Overview': 'Tổng quan',
          'Trends': 'Xu hướng',
          'Categories': 'Danh mục',
          'Add Products': 'Thêm sản phẩm',
          'Week 1': 'Tuần 1',
          'Week 2': 'Tuần 2',
          'Week 3': 'Tuần 3',
          'Week 4': 'Tuần 4',
          'User Statistics': 'Thống kê người dùng',
          'Infinity': 'Vô cực',
          'Role': 'Vai trò:',
          'Feedback Statistics': 'Thống kê phản hồi',
          'Feedback Management': 'Quản lý phản hồi',
          'Total Feedback': 'Tổng số phản hồi',
          'Average Rating': 'Đánh giá trung bình',
          ' +0.3 vs last week': '+0.3 so với tuần trước',
          'Sentiment Analysis': 'Phân tích cảm xúc',
          'Positive': 'Tích cực',
          'Neutral': 'Trung tính',
          'Negative': 'Tiêu cực',
          'Recent Feedback': 'Phản hồi gần đây',
          'Feedback Volume Trend': 'Xu hướng khối lượng phản hồi',
          'Category Distribution': 'Phân phối danh mục',
          'Bug': 'Lỗi',
          'Feature': 'Tính năng',
          'Other': 'Khác',
          'Rating:': 'Đánh giá',
          'Add Product': 'Thêm sản phẩm',
          'This Month': 'trong tháng này', // Để sử dụng trong câu
          'Advanced Analytics Dashboard': 'Trang tổng quan phân tích nâng cao',
          'Gallery': 'Thư viện',
          'Message': 'Tin nhắn',
          'home': 'Trang chủ',
          'Background': 'Hình nền',
          'Choose_your_background': "Chọn nền phòng",
          'Please_select_background': 'Bạn chưa chọn nền phòng',
          'Products list to design': 'Sản phảm dùng thiết kế',
          'go_add_product' : 'Vào doanh mục sản phẩm để thêm',
          'Our background' : 'Hình nền',
          'Your background' : 'Hình nền của bạn',
          'Loading': 'Đang Tải...',
          'Failed to load image': 'Tải hình ảnh không thành công',
          'Image View': 'Xem hình ảnh',
          'Hello': 'Xin chào',
          'Title': 'Tiêu đề',
          'Sub': 'Đăng ký ngay',
          'Changelang': 'Thay đổi ngôn ngữ',
          'Language': 'Ngôn ngữ',
          'Product': 'Sản phẩm',
          'Messages': 'Tin nhắn',
          'Show Design': 'Hiển thị thiết kế của bạn',
          'Post': 'Đăng',
          'Image upload failed': 'Tải ảnh lên thất bại.',
          'Following': 'Đang theo dõi',
          'Nothing here': 'Không có gì ở đây',
          'Failed to upload image': 'Tải ảnh lên không thành công',
          'Settings': 'Cài đặt',
          'Logout': 'Đăng xuất',
          'For you': 'Dành cho bạn',
          'Brand': 'Thương hiệu: ',
          'Price': 'Giá:',
          'Description': 'Mô tả: ',
          'Item already exists': 'Sản phẩm đã được thêm ',
          'Close': 'Đóng',
          'Designers': 'Các Nhà Thiết Kế',
          'Add new designer': 'Thêm Nhà Thiết Kế Mới',
          'Edit designer': 'Chỉnh Sửa Nhà Thiết Kế',
          'User': 'Người Dùng',
          'Full name': 'Họ và Tên',
          'Years of experience': 'Số Năm Kinh Nghiệm',
          'Specialization': 'Chuyên Ngành',
          'Add': 'Thêm',
          'Item added': 'Đã thêm sản phẩm',
          'Update': 'Cập Nhật',
          'Cancel': 'Hủy',
          'Error': 'Lỗi',
          'design': 'Thiết kế',
          'No designers': 'Không có nhà thiết kế nào.',
          'failed to load designer': 'Không thể tải nhà thiết kế: ',
          'Failed to save designer': 'Không thể lưu nhà thiết kế: ',
          'Failed to delete designer': 'Không thể xóa nhà thiết kế: ',
          'An error occurred': 'Đã xảy ra lỗi: ',
          'Type a message': 'Gõ một tin nhắn',
          'feedback Message': 'Tin Nhắn Phản Hồi',
          'Feedback management': 'Quản Lý Phản Hồi',
          'Something went wrong': 'Đã xảy ra lỗi',
          'write a reply': 'Viết một phản hồi...',
          'Add product': 'Thêm Sản Phẩm',
          'Update product': 'Cập Nhật Sản Phẩm',
          'Product name': 'Tên Sản Phẩm',
          'Choose image': 'Chọn Hình Ảnh',
          'Failed to delete product': 'Không thể xóa sản phẩm: ',
          'No products available': 'Không có sản phẩm nào.',
          'Failed to save product': 'Không thể lưu sản phẩm: ',
          'Failed to load product': 'Không thể tải sản phẩm: ',
          'Uncategorized': 'Chưa Phân Loại',
          'Search users': 'Tìm Kiếm Người Dùng...',
          'Categories Management': 'Quản Lý Danh Mục',
          'No categories available': 'Không có danh mục nào.',
          'Add new category': 'Thêm Danh Mục Mới',
          'Name': 'Tên',
          'Active': 'Kích Hoạt',
          'Edit category': 'Chỉnh Sửa Danh Mục',
          'Confirm deletion': 'Xác Nhận Xóa',
          'Delete confirmation':
          'Bạn có chắc chắn muốn xóa danh mục này không?',
          'Delete': 'Xóa',
          'Show your design': 'Hiển thị thiết kế của bạn',
          'Image picked': 'Hình ảnh đã được chọn!',
          'Dark Mode': 'Chế độ tối',
          'Blocked users': 'Người dùng bị chặn',
          'Accounts Setting': 'Cài đặt tài khoản',
          'English': 'Tiếng Anh',
          'Vietnamese': 'Tiếng Việt',
          'Delete account': 'Xóa Tài Khoản?',
          'Confirm delete':
          'Bạn có chắc chắn muốn xóa tài khoản của mình không?',
          'Account Settings': 'Cài Đặt Tài Khoản',
          'Delete account button': 'Xóa Tài Khoản',
          'Unlock': 'Mở khóa',
          'Confirm unlock': 'Bạn có muốn mở khóa người dùng này không?',
          'Unblock': 'Mở khóa',
          'Unblock success': 'Mở khóa thành công!',
          'No blocked users': 'Không có người dùng bị chặn..',
          'Edit Bio': 'Chỉnh sửa tiểu sử..',
          'Unfollow': 'Bỏ theo dõi',
          'Unfollowing message':
          'Bạn có muốn bỏ theo dõi người dùng này không?',
          'Yes': 'Có',
          'No posts': 'Không có bài viết..',
          'Bio': 'Tiểu sử',
          'Designs': 'Thiết kế',
          'Please enter name': 'Vui lòng nhập tên của bạn.',
          'Please enter email': 'Vui lòng nhập địa chỉ email của bạn.',
          'Please enter password': 'Vui lòng nhập mật khẩu của bạn.',
          'Passwords do not match': 'Mật khẩu không khớp',
          'Register': 'Đăng ký',
          'Email': 'Email',
          'Password': 'Mật khẩu',
          'Confirm password': 'Xác nhận mật khẩu',
          'Have account': 'Bạn đã có tài khoản?',
          'Login here': 'Đăng nhập tại đây',
          'Reviews': 'Đánh giá',
          'No reviews available': 'Không có đánh giá nào.',
          'Add review': 'Thêm đánh giá',
          'Update review': 'Cập nhật đánh giá',
          'Designer': 'Nhà thiết kế',
          'Comment': 'Bình luận',
          'Failed to delete review': 'Không thể xóa đánh giá: ',
          'Failed to save review': 'Không thể lưu đánh giá: ',
          'Failed toload review': 'Không thể tải đánh giá: ',
          'Update User': 'Cập nhật người dùng',
          'Validation error': 'Lỗi xác thực',
          'Name email required': 'Tên và Email là bắt buộc.',
          'User updated successfully': 'Cập nhật người dùng thành công',
          'Delete user confirmation':
          'Bạn có chắc chắn muốn xóa người dùng này không?',
          'User deleted successfully': 'Người dùng đã được xóa thành công',
          'Failed to delete user':
          'Không thể xóa người dùng. Vui lòng thử lại.',
          'No users found': 'Không tìm thấy người dùng nào.',
          'Hint password': 'Để trống để giữ mật khẩu hiện tại',
          'User role': 'Người dùng',
          'Admin role': 'Quản trị viên',
          'Price range distribution': 'Phân phối theo khoảng giá',
          'Recently added products': 'Sản phẩm vừa thêm',
          'New products': 'Sản phẩm mới',
          'Total products': 'Tổng số sản phẩm',
          'No data for comparison': 'Không có dữ liệu để so sánh',
          'Date unknown': 'Ngày không xác định',
          'Product addition trend': 'Xu hướng thêm sản phẩm',
          'Brand distribution': 'Phân phối thương hiệu',
          'vs last week': 'so với tuần trước',
          'This month': 'trong tháng này',
          'Error loading categories': 'Lỗi khi tải danh mục',
          'No categories found': 'Không tìm thấy danh mục',
          'Unnamed_category': 'Danh mục không tên',
          'No description': 'Không có mô tả',
          'Products in this category': 'Sản phẩm trong danh mục này:',
          'No products in this category':
          'Không có sản phẩm trong danh mục này',
          'Unknown brand': 'Thương hiệu không xác định',
          'Unnamed product': 'Sản phẩm không tên',
          'No products found': 'Không tìm thấy sản phẩm',
          'Submit feedback': 'Gửi phản hồi',
          'Feedback submitted': 'Phản hồi đã được gửi thành công',
          'Something wrong': 'Có gì đó không đúng',
          'Rating': 'Đánh giá:',
          'Reply from': 'Phản hồi từ:',
          'Write reply': 'Viết một phản hồi...',
          'No feedback found': 'Không có phản hồi nào',
          'Recording': 'Đang ghi âm...',
          'Tap to record': 'Chạm vào biểu tượng mic để bắt đầu ghi âm',
          'Please select category': 'Vui lòng chọn một danh mục',
          'No comments yet': 'Chưa có bình luận nào..',
          'Report management': 'Quản Lý Báo Cáo',
          'Username': 'Tên người dùng',
          'Timestamp': 'Thời gian',
          'Notification': 'Thông Báo',
          'Login': 'Đăng Nhập',
          'Forgot password': 'Quên Mật Khẩu?',
          'Enter email': 'Vui lòng nhập địa chỉ email của bạn.',
          'Enter password': 'Vui lòng nhập mật khẩu của bạn.',
          'Email password error': 'Có vấn đề với email/mật khẩu của bạn',
          'Google signin error': 'Có điều gì đó không ổn...',
          'Dont have account': 'Chưa có tài khoản?',
          'Register here': 'Đăng Ký Tại Đây',
          'Enter your email': 'Nhập email của bạn:',
          'Invalid email': 'Địa chỉ email không hợp lệ.',
          'Password reset link sent':
          'Đã gửi liên kết đặt lại mật khẩu thành công.',
          'Failed to send reset link':
          'Không thể gửi liên kết đặt lại mật khẩu',
          'Reset password': 'Đặt lại mật khẩu',
          'Followers': 'Người theo dõi',
          'No followers': 'Không có người theo dõi',
          'No following': 'Không có người đang theo dõi',
          'Users dashboard': 'Bảng điều khiển người dùng',
          'Manage users': 'Quản lý người dùng',
          'Weekly new users': 'Người dùng mới hàng tuần',
          'Monthly new users': 'Người dùng mới hàng tháng',
          'Yearly new users': 'Người dùng mới hàng năm',
          'Monthly retention': 'Tỷ lệ giữ chân hàng tháng',
          'Weekly growth trend': 'Xu hướng tăng trưởng hàng tuần',
          'Recent new users': 'Người dùng mới gần đây',
          'Rrror loading retention': 'Lỗi khi tải dữ liệu giữ chân',
          'No feedback data available': 'Không có dữ liệu phản hồi',
          'Export data': 'Xuất dữ liệu',
          'Feedback volume trend': 'Xu hướng khối lượng phản hồi',
          'Category distribution': 'Phân phối danh mục',
          'Total feedback': 'Tổng phản hồi',
          'Average rating': 'Đánh giá trung bình',
          'Sentiment analysis': 'Phân tích cảm xúc',
          'Recent feedback': 'Phản hồi gần đây',
          'No message': 'Không có tin nhắn',
          'Data exported successfully': 'Dữ liệu đã được xuất thành công',
          'Consultations': 'Tư vấn',
          'Add new consultation': 'Thêm tư vấn mới',
          'Edit consultation': 'Chỉnh sửa tư vấn',
          'Status': 'Trạng thái',
          'Select date': 'Chọn ngày',
          'Date': 'Ngày',
          'Failed to load consultation': 'Lỗi khi tải tư vấn',
          'Failed to save consultation': 'Lỗi khi lưu tư vấn',
          'No consultations available': 'Không có tư vấn nào',
          'Failed to delete consultation': 'Lỗi khi xóa tư vấn',
          'Schedule date': 'Ngày lên lịch',
          'Actions': 'Hành động',
          'Failed to delete note': 'Lỗi khi xóa ghi chú',
          'No notes available': 'Không có ghi chú nào.',
          'day': 'Ngày',
          'week': 'Tuần',
          'month': 'Tháng',
          'year': 'Năm',
          'total products': 'Tổng số sản phẩm',
          'new products': 'Sản phẩm mới',
          'feedbacks': 'Phản hồi',
          'reports': 'Báo cáo',
          'users dashboard': 'Bảng điều khiển người dùng',
          'manage users': 'Quản lý người dùng',
          'yearly new users': 'Người dùng mới hàng năm',
          'monthly retention': 'Tỷ lệ giữ chân hàng tháng',
          'wekly growth trend': 'Xu hướng tăng trưởng hàng tuần',
          'recent new users': 'Người dùng mới gần đây',
          'error loading retention': 'Lỗi khi tải tỷ lệ giữ chân',
          'error loading dashboard data:':
          'Lỗi khi tải dữ liệu bảng điều khiển:',
          'add Products': 'Thêm sản phẩm',
          'week 1': 'Tuần 1',
          'week 2': 'Tuần 2',
          'week 3': 'Tuần 3',
          'week 4': 'Tuần 4',
          'user statistics': 'Thống kê người dùng',
          'infinity': 'Vô cực',
          'feedback statistics': 'Thống kê phản hồi',
          'feedback management': 'Quản lý phản hồi',
          'total feedback': 'Tổng số phản hồi',
          'average rating': 'Đánh giá trung bình',
          'sentiment analysis': 'Phân tích cảm xúc',
          'positive': 'Tích cực',
          'neutral': 'Trung tính',
          'negative': 'Tiêu cực',
          'recent feedback': 'Phản hồi gần đây',
          'feedback volume trend': 'Xu hướng khối lượng phản hồi',
          'category distribution': 'Phân phối danh mục',
          'rating:': 'Đánh giá',
          'add product': 'Thêm sản phẩm',
          'this month': 'trong tháng này',
          'background': 'Hình nền',
          'Choose your background': "Chọn nền phòng",
          'Please select background': 'Bạn chưa chọn nền phòng',
          'products list to design': 'Sản phảm dùng thiết kế',
          'Go add product': 'Vào doanh mục sản phẩm để thêm',
          'No link provided': 'Không có link',
          'D E S I G N' : 'T H I Ế T K Ế',
        },
      };
}
